on: [push]
name: Docker_Build
permissions:
  id-token: write
  contents: read
  
env: 
  APP_DOCKER_IMAGE_NAME: learn-nextjs-docker-app
jobs:
    build-and-deploy-docker-image:
        runs-on: ubuntu-latest
        environment: production
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - uses: cschleiden/replace-tokens@v1
          with:
            files: '.env.sample.production'
          env:
            AZURE_APP_CONFIGURATION_CONNECTION_STRING: ${{ secrets.AZURE_APP_CONFIGURATION_CONNECTION_STRING }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.APP_DOCKER_IMAGE_NAME }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.APP_DOCKER_IMAGE_NAME }}:${{ github.sha }}

    deploy-azure-resources: 
      runs-on: ubuntu-latest
      environment: production
      needs: build-and-deploy-docker-image
      steps: 
        - name: 'Checkout Code'
          uses: actions/checkout@main
          
        # Log into Azure
        - uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Deploy Bicep file
          uses: azure/arm-deploy@v1
          with:
            scope: 'resourcegroup'
            template: ./IaC/build/main.bicep
            resourceGroupName: 'learn-nextjs-rg'
            parameters: 
              dockerRegistryServerPassword=${{ secrets.REGISTRY_PASSWORD }}
              dockerRegistryServerUserName=${{ secrets.REGISTRY_USERNAME }}
              dockerRegistryServerUrl=${{ secrets.REGISTRY_LOGIN_SERVER }}
              learnNextJsAppImageName=${{ env.APP_DOCKER_IMAGE_NAME }}
              learnNextJsAppImageTag=${{ github.sha }}